export const REGISTER_USER_BEGIN = "REGISTER_USER_BEGIN"
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS"
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR"

export const LOGIN_USER_BEGIN = "LOGIN_USER_BEGIN"
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS"
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR"
export const LOGOUT_USER = "LOGOUT_USER"

export const GET_USER_BEGIN = "GET_USER_BEGIN"
export const GET_USER_SUCCESS = "GET_USER_SUCCESS"

export const EDIT_SOCIALS_BEGIN = "EDIT_SOCIALS_BEGIN"
export const EDIT_SOCIALS_SUCCESS = "EDIT_SOCIALS_SUCCESS"
export const EDIT_SOCIALS_ERROR = "EDIT_SOCIALS_ERROR"

export const CHANGE_PW_BEGIN = "CHANGE_PW_BEGIN"
export const CHANGE_PW_SUCCESS = "CHANGE_PW_SUCCESS"
export const CHANGE_PW_ERROR = "CHANGE_PW_ERROR"

export const GET_GITHUBDATA_BEGIN = "GET_GITHUBDATA_BEGIN"
export const GET_GITHUBDATA_SUCCESS = "GET_GITHUBDATA_SUCCESS"
export const GET_GITHUBDATA_ERROR = "GET_GITHUBDATA_ERROR"
