export const REGISTER_USER_BEGIN = "REGISTER_USER_BEGIN"
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS"
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR"

export const LOGIN_USER_BEGIN = "LOGIN_USER_BEGIN"
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS"
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR"
export const LOGOUT_USER = "LOGOUT_USER"

export const GET_USER_BEGIN = "GET_USER_BEGIN"
export const GET_USER_SUCCESS = "GET_USER_SUCCESS"

export const EDIT_SOCIALS_BEGIN = "EDIT_SOCIALS_BEGIN"
export const EDIT_SOCIALS_SUCCESS = "EDIT_SOCIALS_SUCCESS"
export const EDIT_SOCIALS_ERROR = "EDIT_SOCIALS_ERROR"

export const CHANGE_PW_BEGIN = "CHANGE_PW_BEGIN"
export const CHANGE_PW_SUCCESS = "CHANGE_PW_SUCCESS"
export const CHANGE_PW_ERROR = "CHANGE_PW_ERROR"

export const GET_GITHUBDATA_BEGIN = "GET_GITHUBDATA_BEGIN"
export const GET_GITHUBDATA_SUCCESS = "GET_GITHUBDATA_SUCCESS"
export const GET_GITHUBDATA_ERROR = "GET_GITHUBDATA_ERROR"

export const GET_HACKERRANKDATA_BEGIN = "GET_HACKERRANKDATA_BEGIN"
export const GET_HACKERRANKDATA_SUCCESS = "GET_HACKERRANKDATA_SUCCESS"
export const GET_HACKERRANKDATA_ERROR = "GET_HACKERRANKDATA_ERROR"

export const GET_CODECHEFDATA_BEGIN = "GET_CODECHEFDATA_BEGIN"
export const GET_CODECHEFDATA_SUCCESS = "GET_CODECHEFDATA_SUCCESS"
export const GET_CODECHEFDATA_ERROR = "GET_CODECHEFDATA_ERROR"

export const SEARCH_USER_BEGIN = "SEARCH_USER_BEGIN"
export const SEARCH_USER_SUCCESS = "SEARCH_USER_SUCCESS"
export const SEARCH_USER_ERROR = "SEARCH_USER_ERROR"

export const ADD_FRIEND_BEGIN = "ADD_FRIEND_BEGIN"
export const ADD_FRIEND_SUCCESS = "ADD_FRIEND_SUCCESS"
export const ADD_FRIEND_ERROR = "ADD_FRIEND_ERROR"

export const GET_PENDING_REQ_BEGIN = "GET_PENDING_REQ_BEGIN"
export const GET_PENDING_REQ_SUCCESS = "GET_PENDING_REQ_SUCCESS"
export const GET_PENDING_REQ_ERROR = "GET_PENDING_REQ_ERROR"

export const GET_CANCEL_REQ_BEGIN = "GET_CANCEL_REQ_BEGIN"
export const GET_CANCEL_REQ_SUCCESS = "GET_CANCEL_REQ_SUCCESS"

export const GET_ACCEPT_REQ_BEGIN = "GET_ACCEPT_REQ_BEGIN"
export const GET_ACCEPT_REQ_SUCCESS = "GET_ACCEPT_REQ_SUCCESS"

export const GET_FRIENDS_REQ_BEGIN = "GET_FRIENDS_REQ_BEGIN"
export const GET_FRIENDS_REQ_SUCCESS = "GET_FRIENDS_REQ_SUCCESS"
export const GET_FRIENDS_REQ_ERROR = "GET_FRIENDS_REQ_ERROR"

export const GET_REQUESTS_REQ_BEGIN = "GET_REQUESTS_REQ_BEGIN"
export const GET_REQUESTS_REQ_SUCCESS = "GET_REQUESTS_REQ_SUCCESS"
export const GET_REQUESTS_REQ_ERROR = "GET_REQUESTS_REQ_ERROR"
